#!/usr/bin/python3
import ldap3
import argparse
import logging

log_levels = {
    "CRITICAL": logging.CRITICAL,
    "ERROR": logging.ERROR,
    "WARNING": logging.WARNING,
    "INFO": logging.INFO,
    "DEBUG": logging.DEBUG
}

ap = argparse.ArgumentParser(description = "Manage LDAP accounts")

ap.add_argument("--loglevel",
        dest = "log_level",
        default = "WARNING",
        type = str,
        choices = log_levels.keys(),
        help = "Set logging verbosity")

modes = ap.add_subparsers(title = "Objects to manage")

# User commands

p_user = modes.add_parser("user",
        help = "User accounts")

sp_user = p_user.add_subparsers(title = "User command")

sp_user.add_parser("list")

p_user_search = sp_user.add_parser("search",
        aliases = ["find", "grep"])

p_user_search.add_argument("pattern",
        metavar = "PATTERN",
        help = "Search pattern")

sp_user.add_parser("show",
        aliases = ["info"],
        help = "Show details for the accounts")

p_user_suspend = sp_user.add_parser("suspend",
        aliases = ["lock", "ban", "disable"],
        help = "Make the accounts inactive")

p_user_restore = sp_user.add_parser("restore",
        aliases = ["unlock", "unban", "enable"],
        help = "Re-activate the accounts")

p_user_delete = sp_user.add_parser("add",
        aliases = ["create"],
        help = "Add a new account")

# List commands

p_list = modes.add_parser("list",
        help = "Mailing lists")

ap.parse_args()
